# Generated by Django 5.1.2 on 2024-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
